sudo: required #관리자 권한

language: generic #언어

services:
  - docker

before_install: #스크립트를 실행할 수 있는 환경 구성
  - echo "start Creating an image with dockerfile"
  - docker build -t hhss2259/docker-react-app -f Dockerfile.dev ./

script: #실행할 스크립트
  - docker run -e CI=true hhss2259/docker-react-app npm run test -- --coverage

after_success: #테스트 성공 후 할 일
  - echo "Test Success"



